name : workspace
on : [push]
jobs : 
  repo:
    runs-on : ubuntu-latest
    steps :
      - uses : actions/checkout@v2
      - uses : actions/setup-node@v2
        with :
          node-version : '14.17.0'
      - name : Folder tree Structure
        run : tree

      - name : Installing Dependency and Build files
        run : npm install && npm run build
