name : first-workspace
on : [push]
jobs : 
  test-set-1 :
    runs-on : ubuntu-latest
    steps :
      - run : echo "hello world !!"
      - run : echo "yo jogender thara bhai jogender"

  test-set-2 :
    runs-on : ubuntu-latest
    steps :
      - run : echo "hello world 2 !!"