name : workspace
on : [push]
jobs : 
  repo:
    runs-on : ubuntu-latest
    steps :
      - uses : actions/checkout@v2
      - uses : actions/setup-node@v2
      - run : tree
      - run : npm install && npm start
      - run : echo "hello world"